
-- MASV: 49.01.104.120
-- HO TEN: Nguyen Huu Minh Quan
-- LAB: 03
-- NGAY 4/3/2025
--DROP DATABASE QLSV

USE QLSV

-- MASV: 49.01.104.120
-- HO TEN: Nguyen Huu Minh Quan
-- LAB: 03
-- NGAY 4/3/2025
CREATE TABLE NHANVIEN(
    MANV VARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    EMAIL NVARCHAR(20),
    LUONG VARBINARY(MAX),
    TENDN NVARCHAR(100) NOT NULL,
    MATKHAU VARBINARY(MAX) NOT NULL
)

-- MASV: 49.01.104.120
-- HO TEN: Nguyen Huu Minh Quan
-- LAB: 03
-- NGAY 4/3/2025
GO
CREATE TABLE LOP(
    MALOP VARCHAR(20) PRIMARY KEY,
    TENLOP NVARCHAR(100) NOT NULL,
    MANV VARCHAR(20)
)

-- MASV: 49.01.104.120
-- HO TEN: Nguyen Huu Minh Quan
-- LAB: 03
-- NGAY 4/3/2025
GO
CREATE TABLE SINHVIEN(
    MASV NVARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATETIME,
    DIACHI NVARCHAR(200),
    MALOP VARCHAR(20),
    TENDN NVARCHAR(100) NOT NULL,
    MATKHAU VARBINARY(MAX) NOT NULL
)

-- MASV: 49.01.104.120
-- HO TEN: Nguyen Huu Minh Quan
-- LAB: 03
-- NGAY 4/3/2025
GO
CREATE MASTER KEY ENCRYPTION BY PASSWORD = '4901104120';
GO
CREATE CERTIFICATE MyCertificate WITH SUBJECT = 'Data Encryption';

-- Tạo Symmetric Key dùng AES-256 với khóa '4901104120'
GO
CREATE SYMMETRIC KEY MySymmetricKey  
WITH ALGORITHM = AES_256  
ENCRYPTION BY PASSWORD = '4901104120';

-- MASV: 49.01.104.120
-- HO TEN: Nguyen Huu Minh Quan
-- LAB: 03
-- NGAY 4/3/2025
GO
CREATE PROCEDURE SP_INS_SINHVIEN
    @MASV NVARCHAR(20),
    @HOTEN NVARCHAR(100),
    @NGAYSINH DATETIME,
    @DIACHI NVARCHAR(200),
    @MALOP VARCHAR(20),
    @TENDN NVARCHAR(100),
    @MATKHAU NVARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;

    -- Mã hóa mật khẩu bằng MD5
    DECLARE @EncryptedPassword VARBINARY(16);
    SET @EncryptedPassword = HASHBYTES('MD5', @MATKHAU);

    -- Thêm dữ liệu vào bảng SINHVIEN
    INSERT INTO SINHVIEN (MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN, MATKHAU)
    VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, @EncryptedPassword);
END;

GO
EXEC SP_INS_SINHVIEN 'SV01', 'NGUYEN VAN A', '1/1/1990', '280 AN DUONG VUONG', 'CNTT-K35', 'NVA','123456'


-- MASV: 49.01.104.120
-- HO TEN: Nguyen Huu Minh Quan
-- LAB: 03
-- NGAY 4/3/2025
GO
CREATE PROCEDURE SP_INS_NHANVIEN 
    @MANV VARCHAR(50),
    @HOTEN NVARCHAR(255),
    @EMAIL VARCHAR(255),
    @LUONG DECIMAL(18, 2),
    @TENDN VARCHAR(50),
    @MATKHAU VARCHAR(255)
AS
BEGIN
    SET NOCOUNT ON;

    -- Mở khóa đối xứng
    OPEN SYMMETRIC KEY MySymmetricKey DECRYPTION BY PASSWORD = '4901104120';

    -- Mã hóa mật khẩu bằng SHA1
    DECLARE @HashedPassword VARBINARY(20);
    SET @HashedPassword = HASHBYTES('SHA1', @MATKHAU);

    -- Mã hóa lương bằng AES
    DECLARE @EncryptedLuong VARBINARY(MAX);
    SET @EncryptedLuong = ENCRYPTBYKEY(KEY_GUID('MySymmetricKey'), CAST(@LUONG AS VARBINARY));

    -- Thêm dữ liệu vào bảng NHANVIEN
    INSERT INTO NHANVIEN (MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU)
    VALUES (@MANV, @HOTEN, @EMAIL, @EncryptedLuong, @TENDN, @HashedPassword);

    -- Đóng khóa đối xứng
    CLOSE SYMMETRIC KEY MySymmetricKey;
END;
GO
EXEC SP_INS_NHANVIEN 'NV02', 'NGUYEN VAN B', 'NVB@', 300000, 'NVB', 'abcd12'

GO

-- MASV: 49.01.104.120
-- HO TEN: Nguyen Huu Minh Quan
-- LAB: 03
-- NGAY 4/3/2025
CREATE PROCEDURE SP_SEL_NHANVIEN
AS
BEGIN
    SET NOCOUNT ON;

    -- Mở khóa đối xứng
    OPEN SYMMETRIC KEY MySymmetricKey DECRYPTION BY PASSWORD = '4901104120';

    -- Lấy danh sách nhân viên và giải mã lương
    SELECT
        MANV,
        HOTEN,
        EMAIL,
        CONVERT(DECIMAL(18, 2), DECRYPTBYKEY(LUONG)) AS LUONGCB
    FROM
        NHANVIEN;

    -- Đóng khóa đối xứng
    CLOSE SYMMETRIC KEY MySymmetricKey;
END;
GO
EXEC SP_SEL_NHANVIEN