/*----------------------------------------------------------
MASV: 4901104120
HO TEN: NGUYEN HUU MINH QUAN
LAB: 04
NGAY: 05/08/2025
----------------------------------------------------------*/
CREATE DATABASE QLSV
GO
USE QLSV
GO
-- CREATE TABLES SINHVIEN
CREATE TABLE SINHVIEN(
	MASV NVARCHAR(20) NOT NULL,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(100) NOT NULL,
	PRIMARY KEY(MASV)
	)
-- CREATE TABLES NHANVIEN
GO
CREATE TABLE NHANVIEN(
	MANV VARCHAR(20) NOT NULL,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(100),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(100) NOT NULL,
	PRIMARY KEY(MANV)
	)
-- CREATE TABLES LOP
GO
CREATE TABLE LOP(
	MALOP VARCHAR(20) NOT NULL,
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20),
	PRIMARY KEY(MALOP)
	)

GO
-- Câu c: i:
GO
CREATE PROCEDURE dbo.SP_INS_ENCRYPT_SINHVIEN
	@MASV NVARCHAR(20),
	@HOTEN NVARCHAR(100),
	@NGAYSINH DATETIME,
	@DIACHI NVARCHAR(200),
	@MALOP VARCHAR(20),
	@TENDN NVARCHAR(100),
	@MATKHAU varbinary
AS
BEGIN
	INSERT INTO SINHVIEN(MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN, MATKHAU)
	VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, @MATKHAU)
END

-- ii
GO
CREATE PROCEDURE SP_INS_ENCRYPT_NHANVIEN
	@MANV VARCHAR(20),
	@HOTEN NVARCHAR(100),
	@EMAIL VARCHAR(20),
	@LUONG varbinary(max),
	@TENDN NVARCHAR(100),
	@MATKHAU varbinary(max)
AS
BEGIN
    INSERT INTO NHANVIEN (MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU)
    VALUES (@MANV, @HOTEN, @EMAIL,  @LUONG, @TENDN, @MATKHAU);
END

-- iii
GO
CREATE PROCEDURE SP_SEL_ENCRYPT_NHANVIEN
AS
BEGIN
	SELECT NV.MANV, NV.HOTEN, NV.EMAIL,NV.LUONG as LUONG
	FROM NHANVIEN AS NV
END
GO 

-- Update nhanvien
CREATE PROCEDURE SP_UPD_ENCRYPT_NHANVIEN
	@MANV VARCHAR(20),
	@HOTEN NVARCHAR(100),
	@EMAIL VARCHAR(20),
	@LUONG varbinary(max),
	@TENDN NVARCHAR(100),
	@MATKHAU varbinary(max)
AS
BEGIN
    UPDATE NHANVIEN
    set HOTEN = @HOTEN, EMAIL = @EMAIL, LUONG =  @LUONG, TENDN = @TENDN, MATKHAU = @MATKHAU
	where MANV = @MANV
END

-- Them nhanvien
GO
DECLARE @p VARBINARY(MAX);
DECLARE @l VARBINARY(MAX);
SET @p = 0xA665A45920422F9D417E4867EFDC4FB8A04A1F3FFF1FA07E998E86F7F7A27AE3 --123
SET @l = 0x6E8BA1C51F0E8FD56806F5F35E4B38A9 --20000 + key:4901104120

EXEC SP_INS_ENCRYPT_NHANVIEN 'NV01','NGUYEN VAN A','NVA@',@l,'NVA',@p;