use QLBongDa

-- Tạo bdadmin
CREATE LOGIN BDAdmin WITH PASSWORD = '4901104120'
CREATE USER BDAdmin FOR LOGIN BDAdmin
ALTER ROLE db_owner ADD MEMBER BDAdmin

-- Tạo bdbk
CREATE LOGIN BDBK WITH PASSWORD = 'BKup'
CREATE USER BDBK FOR LOGIN BDBK
GRANT BACKUP DATABASE TO BDBK

-- Tạo bdread
CREATE LOGIN BDRead WITH PASSWORD = 'Read'
CREATE USER BDRead FOR LOGIN BDRead
GRANT SELECT ON SCHEMA::dbo TO BDRead

-- Tạo BDU01
CREATE LOGIN BDU01 WITH PASSWORD = 'BDU01'
CREATE USER BDU01 FOR LOGIN BDU01
GRANT CREATE TABLE TO BDU01

-- Tạo BDU02
CREATE LOGIN BDU02 WITH PASSWORD = 'BDU02'
CREATE USER BDU02 FOR LOGIN BDU02
GRANT UPDATE TO BDU02
DENY CREATE TABLE TO BDU02
DENY CONTROL ON SCHEMA::dbo TO BDU02

-- Tạo BDU03
CREATE LOGIN BDU03 WITH PASSWORD = 'BDU03'
CREATE USER BDU03 FOR LOGIN BDU03
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.CauLacBo TO BDU03

-- Tạo BDU04
CREATE LOGIN BDU04 WITH PASSWORD = 'BDU04'
CREATE USER BDU04 FOR LOGIN BDU04
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.CAUTHU TO BDU04
DENY SELECT ON dbo.CAUTHU(NGAYSINH) TO BDU04
DENY UPDATE ON dbo.CAUTHU(VITRI) TO BDU04

-- Tạo BDProfile
CREATE LOGIN BDProfile WITH PASSWORD = 'BDProfile'
CREATE USER BDProfile FOR LOGIN BDProfile
GRANT ALTER TRACE TO BDProfile;