/*----------------------------------------------
MASV:
HO TEN CAC THANH VIEN NHOM:
LAB: 03 - NHOM
NGAY:
----------------------------------------------*/

CREATE DATABASE QLSVNhom
-- DROP DATABASE QLSVNHOM

GO
CREATE TABLE SINHVIEN(
    MASV NVARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATETIME,
    DIACHI NVARCHAR(200),
    MALOP VARCHAR(20),
    EMAIL NVARCHAR(20),
    TENDN NVARCHAR(100) NOT NULL,
    MATKHAU VARBINARY(MAX) NOT NULL
)
-- DROP TABLE SINHVIEN
GO
CREATE TABLE NHANVIEN(
    MANV VARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    EMAIL NVARCHAR(20),
    LUONG VARBINARY(MAX),
    TENDN NVARCHAR(100) NOT NULL,
    MATKHAU VARBINARY(MAX) NOT NULL,
    PUBKEY VARCHAR(20)
)
-- DROP TABLE NHANVIEN

GO
CREATE TABLE LOP(
    MALOP VARCHAR(20) PRIMARY KEY,
    TENLOP NVARCHAR(100) NOT NULL,
    MANV VARCHAR(20)
)
-- DROP TABLE LOP

GO
CREATE TABLE HOCPHAN(
    MAHP VARCHAR(20), PRIMARY KEY,
    TENHP NVARCHAR(100) NOT NULL,
    SOTC INT
)
-- DROP TABLE HOCPHAN

GO
CREATE TABLE BANGDIEM (
    MASV VARCHAR(20),
    MAHP VARCHAR(20),
    DIEMTHI VARBINARY(MAX),
    FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
    FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP)
);
-- DROP TABLE BANGDIEM
GO
CREATE PROCEDURE SP_INS_PUBLIC_NHANVIEN
    @MANV VARCHAR(20),
    @HOTEN NVARCHAR(255),
    @EMAIL NVARCHAR(255),
    @LUONG DECIMAL(18, 2),
    @TENDN NVARCHAR(50),
    @MATKHAU VARCHAR(255)
AS
BEGIN
    SET NOCOUNT ON;

    -- Còn làm tiếp


    DECLARE @HashedPassword VARBINARY(20);
    SET @HashedPassword = HASHBYTES('SHA1', @MATKHAU);

    DECLARE @PubKey NVARCHAR(100)
    SET @PubKey = @MaNV
    INSERT INTO SINHVIEN(MANV, HOTEN, MATKHAU, LUONG, PUBKEY)

END;

GO
EXEC SP_INS_PUBLIC_NHANVIEN ‘NV01’, ‘NGUYEN VAN A’, ‘NVA@’, 
3000000, ‘NVA’, ‘abcd12’

GO
CREATE PROCEDURE SP_SEL_PUBLIC_NHANVIEN
    @TENDN NVARCHAR(50),
    @MATKHAU VARCHAR(255)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT *
    FROM NHANVIEN
    WHERE TENDN = @TENDN AND MATKHAU = @MATKHAU
    -- CÒN làm tiếp
END

GO
EXEC SP_SEL_PUBLIC_NHANVIEN ‘NV01’, ‘abcd12’
